#################################################################
# +-----------------------------------------------------------+ #
# |                        ConsoleLink                        | #
# |                  Made with <3 by sieadev                  | #
# +-----------------------------------------------------------+ #
#################################################################

console_channels:
  '1307414690489565296': '1308339251334746112'