#################################################################
# +-----------------------------------------------------------+ #
# |                        ConsoleLink                        | #
# |         Made with <3 by Sieadev at Pixel Services         | #
# +-----------------------------------------------------------+ #
#################################################################

command-forwarding: true

linked-channels: []