#################################################################
# +-----------------------------------------------------------+ #
# |                         QuickVoice                        | #
# |                  Made with <3 by sieadev                  | #
# +-----------------------------------------------------------+ #
#################################################################