#################################################################
# +-----------------------------------------------------------+ #
# |                      EmbedGenerator                       | #
# |          Made with <3 by Relism at Pixel Services         | #
# +-----------------------------------------------------------+ #
#################################################################