#################################################################
# +-----------------------------------------------------------+ #
# |                          Tickets                          | #
# |                  Made with <3 by sieadev                  | #
# +-----------------------------------------------------------+ #
#################################################################

# -------------------------- Tickets -------------------------- #
delete_on_close: true

# ------------------------- Messages -------------------------- #
messages:
  # The message that will be sent when a ticket is created
  created: 'Hello %user%! How can we help you today? Please describe your issue and a moderator will be with you shortly.'

  # The message that will be sent when a ticket is claimed
  claimed: 'Ticket claimed by %moderator%'

  # The message that will be sent when a ticket is closed
  close: 'Ticket closed by %moderator%'

# -------------------------- Storage -------------------------- #
# Save messages
save_messages_to_db: true

# Archive completed tickets
archive_completed_tickets: true

# MYSQL or FILE
type: "FILE"

credentials:
  url: "jdbc:mysql://localhost:3306/your_database"
  user: "user"
  password: "password"
