#################################################################
# +-----------------------------------------------------------+ #
# |                        StatusModule                       | #
# |                  Made with <3 by sieadev                  | #
# +-----------------------------------------------------------+ #
#################################################################

activity:
  type: 'LISTENING'
  details: 'Cool Music'
  streaming_url: https://www.twitch.tv/ssiea