#################################################################
# +-----------------------------------------------------------+ #
# |                       CountingModule                      | #
# |                  Made with <3 by sieadev                  | #
# +-----------------------------------------------------------+ #
#################################################################

channel_id: CHANNEL_ID # The channel ID where the counting should take place
count-along-after-seconds: 30 # Set to negative to disable
allow-same-user-count: false
