#################################################################
# +-----------------------------------------------------------+ #
# |                          Welcome                          | #
# |        Made with <3 by SamVolvo at Pixel Services         | #
# +-----------------------------------------------------------+ #
#################################################################

# Give us the textChannel id's you wanne use.
channel:
  welcome: ""
  leave: ""