#################################################################
# +-----------------------------------------------------------+ #
# |                       Ticket System                       | #
# |        Made with <3 by SamVolvo at Pixel Services         | #
# +-----------------------------------------------------------+ #
#################################################################


# The names that will be used to search for or create a category if not found.
names:
# This category will store all open tickets and the ticket channel.
  ticket-category: "📩Tickets📩"
# The category the tickets will be stored when closed.
  archive-category: "📦Archive📦"
# In this channel the member will be able to press a button to create a ticket.
  ticket-channel: "➕Ticket➕"
